### ISSUE TITLE
How to get access to the dataset?

### ISSUE THREAD

**Issue by BG4WCE** [HKUST-DRIVE-AI-LAB/FollowNet#1]
Hi,
Thanks for sharing your work. I could not access the data saved on your sharepoint, do I need to apply the access somewhere?

**Comment by Xianda-Chen** [comment]
Dear Feng Liu,

Thank you for your interest in our work and for reading our paper "FollowNet: A comprehensive Benchmark for Car-Following Behavior Modeling." We appreciate your positive feedback.

Now the data is available for download. If you have any further questions or would like to learn more about our research, please feel free to let me know.

Thank you again for your interest and support!

Best regards,
Xianda

________________________________
发件人: Feng Liu ***@***.***>
发送时间: 2023年8月25日 19:22
收件人: HKUST-DRIVE-AI-LAB/FollowNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HKUST-DRIVE-AI-LAB/FollowNet] How to get access to the dataset? (Issue #1)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

Hi,
Thanks for sharing your work. I could not access the data saved on your sharepoint, do I need to apply the access somewhere?

―
