### ISSUE TITLE
Colab里，最后一个单元格的代码运行不了，需要修改

### ISSUE THREAD

**Issue by levisocool** [HKUST-DRIVE-AI-LAB/FollowNet#11]
1、首先，缺少了count 、col 和error_list  的初始化，如下。
count = 0
col = 0
error_list = []

2、代码再次运行后，出现下述错误：
ValueError                                Traceback (most recent call last)
[<ipython-input-10-bf1a4a6ec6ae>](https://localhost:8080/#) in <cell line: 32>()
     66             # print(sv_spd_)
     67             MyDevice = torch.device('cuda:0')
---> 68             sv_spd_ = torch.tensor(max(np.array(sv_spd_.detach().cpu()),[0.001]), device=MyDevice)
     69 
     70             delta_v_ = lv_spd[frame + 1] - sv_spd_

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

3、通过改成“sv_spd_ = sv_spd_.detach().clamp(min=0.001).to(MyDevice)”，修复了上述问题后，还是出现：

TypeError                                 Traceback (most recent call last)
[<ipython-input-12-35c8eacdb377>](https://localhost:8080/#) in <cell line: 32>()
     72             spacing_ = x_data[frame, :, 0] + Ts*(delta_v + delta_v_)/2
     73 
---> 74             if float(np.array(spacing_.cpu())) <= 0:
     75                 col += 1
     76                 break

TypeError: only length-1 arrays can be converted to Python scalars

后续还会有几处张量标量转化的问题，希望有空可以看看，谢谢！

**Comment by Xianda-Chen** [comment]
Thanks for your feedback!

**Comment by levisocool** [comment]
> Thanks for your feedback!

请问啥时候会修改好，因为里面有些逻辑我也没法确认自己是不是改对了。期待你修复后的可运行的代码

**Comment by levisocool** [comment]
@Xianda-Chen 

> > Thanks for your feedback!
> 
> 请问啥时候会修改好，因为里面有些逻辑我也没法确认自己是不是改对了。期待你修复后的可运行的代码
