### ISSUE TITLE
Can't access the dataset

### ISSUE THREAD

**Issue by xiedanmu** [HKUST-DRIVE-AI-LAB/FollowNet#3]
Hi,
Thanks for sharing your work. I could not access the data saved on your sharepoint, do I need to apply the access somewhere?

It said"This link has been removed. Sorry, access to this document has been removed. Please contact the person who shared it with you."

Could you please reshare the dataset?

**Comment by fisher75** [comment]
same problem here? Any other available options as for CF datasets?

**Comment by Xianda-Chen** [comment]
solved, plz check the updated link

**Comment by fisher75** [comment]
> solved, plz check the updated link

hi bro, may I add you on WeChat? Talk about some use of this dataset.

**Comment by Xianda-Chen** [comment]
> > solved, plz check the updated link
> 
> hi bro, may I add you on WeChat? Talk about some use of this dataset.

ok, plz email me.

**Comment by fisher75** [comment]
> > > solved, plz check the updated link
> > 
> > 
> > hi bro, may I add you on WeChat? Talk about some use of this dataset.
> 
> ok, plz email me.


Can't find your email.

**Comment by Xianda-Chen** [comment]
> > > > solved, plz check the updated link
> > > 
> > > 
> > > hi bro, may I add you on WeChat? Talk about some use of this dataset.
> > 
> > 
> > ok, plz email me.
> 
> Can't find your email.

xchen595@connect.hkust-gz.edu.cn
