### ISSUE TITLE
How to calculate the four key metrics to evaluate the performance of car-following models?

### ISSUE THREAD

**Issue by wangrocket** [HKUST-DRIVE-AI-LAB/FollowNet#4]
Dear Professor Chen :
       I am a graduate student from Tongi University. Thank you for your paper and the dataset and code you shared. I have had some trouble trying to reproduce the four key metrics for evaluating the performance of car-following models proposed in your paper. lf possible, could you please share with me the code of how to calculate the four key metrics? My email is "wshj20010610@163.com”.
      The best wishes to you!

**Comment by Xianda-Chen** [comment]
Updated in the Colab tutorial.
