### ISSUE TITLE
请教下数据集的含义和单位

### ISSUE THREAD

**Issue by levisocool** [HKUST-DRIVE-AI-LAB/FollowNet#8]
首先谢谢作者原意公开数据集，感谢。
想请教下数据集中4个特征（字段）的顺序和单位依次是如下么？
spacing (m)、
FV's speed (m s-1)、
relative speed (m s-1)、
acceleration of the FV (km h-1 s-1)

还是说如论文图三中给的单位
spacing (m)、
FV's speed (km h-1)、
relative speed (m s-1)、
acceleration of the FV (m s-2)

另外，好奇论文图3为何用不同的图例，按理统一图例会更方便对比和查看。

**Comment by Xianda-Chen** [comment]
Thanks for your question and recognition. Please refer to the provided Colab tutorial for more details.
